name: gh-packages
run-name: ${{ github.actor }} has executed 'misc--gh-packages.yml' â„–${{ github.run_number }}
on: workflow_dispatch

jobs:
  gh-packages:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the latest version of repo in '${{ github.ref }}'"
        uses: actions/checkout@v4

      - name: "Set up JDK 25 (Amazon Corretto)"
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: pom.xml
          server-id: maven-central
          server-username: MAVEN__CENTRAL_USERNAME
          server-password: MAVEN__CENTRAL_PASSWORD

      - name: "Compile 'th-tool' (no tests and no JARs and JavaDoc):"
        run: mvn test-compile

      - name: "Display the effective maven settings"
        env:
          MAVEN__CENTRAL_USERNAME: ${{ secrets.MAVEN__CENTRAL_USERNAME }}
          MAVEN__CENTRAL_PASSWORD: ${{ secrets.MAVEN__CENTRAL_PASSWORD }}
        run: |
          # save the effective-settings into './target/effective-settings.xml':
          mvn help:effective-settings -DshowPasswords=true -Doutput=./target/effective-settings.xml
          # print the effective-settings in summary:
          echo "<details><summary><code>effective-settings.xml</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`xml" >> $GITHUB_STEP_SUMMARY
          cat ./target/effective-settings.xml >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

      - name: "Executing bash-scripts to fetch the information about current GH-Package and render it as a summary:"
        env:
          # it's very important to set the env-var 'GH_TOKEN' in order to use "gh"-cli utility!
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/scripts/gh-api--get-package.sh
          .github/scripts/gh-api--list-package-versions-all.sh

