name: gpg-demo
run-name: ${{ github.actor }} has executed 'misc--gpg.yml' â„–${{ github.run_number }}
on: workflow_dispatch

jobs:
  gpg-demo:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the latest version of repo in '${{ github.ref }}'"
        uses: actions/checkout@v4

      - name: "Set up JDK 25 (Amazon Corretto)"
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: pom.xml

      - name: "Display the information about 'gpg'-utility version:"
        run: |
          echo "## Current status of GPG-storage" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

          echo "- getting the version of 'gpg'-utility:"
          gpg --version
          echo "<details><summary><code>gpg --version</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          gpg --version >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

          echo "- getting the version of 'bash':"
          bash --version
          echo "<details><summary><code>bash --version</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          bash --version >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

      - name: "Configure GPG Key (import and trust):"
        run: .github/gpg/gpg-import.sh
        env:
          GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: "Display the current status of local GPG-storage:"
        run: |
          echo "- getting the list of available GPG-keys (in 'long'-format):"
          gpg --list-secret-keys --keyid-format=long
          echo "<details><summary><code>gpg --list-secret-keys --keyid-format=long</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          gpg --list-secret-keys --keyid-format=long &>> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

          echo "- getting the list of available GPG-signatures (in '0xshort'-format):"
          gpg --list-signatures --keyid-format 0xshort
          echo "<details><summary><code>gpg --list-signatures --keyid-format 0xshort</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          gpg --list-signatures --keyid-format 0xshort &>> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

      - name: "Signing the file 'pom.xml':"
        env:
          GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "## Signing the file \`pom.xml\`" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

          # invoke 'gpg ... --sign ...':
          .github/gpg/gpg-sign--asc.sh pom.xml

          # invoke 'gpg ... --verify ...':
          .github/gpg/gpg-verify.sh pom.xml.asc

      - name: "Signing the file 'LICENSE':"
        env:
          GPG_KEY_ID: ${{ vars.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "## Signing the file \`LICENSE\`" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

          # invoke 'gpg ... --sign ...':
          .github/gpg/gpg-sign--asc.sh LICENSE

          # invoke 'gpg ... --verify ...':
          .github/gpg/gpg-verify.sh LICENSE.asc
