name: gpg-demo
run-name: ${{ github.actor }} has executed 'misc--gpg.yml' â„–${{ github.run_number }}
on: workflow_dispatch

jobs:
  gpg-demo:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout the latest version of repo in '${{ github.ref }}'"
        uses: actions/checkout@v4

      - name: "Set up JDK 25 (Amazon Corretto)"
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'
          cache-dependency-path: pom.xml

      - name: "Display the information about 'gpg'-utility version:"
        run: |
          echo "## Current status of GPG-storage" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

          echo "- getting the version of 'gpg'-utility:"
          gpg --version
          echo "<details><summary><code>gpg --version</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`xml" >> $GITHUB_STEP_SUMMARY
          gpg --version >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

      - name: "Configure GPG Key:"
        run: |
          # save a passphrase in a text-file:
          echo "1qaz@WSX0okm(IJN" > passphrase.txt
          # Import GPG-keys from GitHub-secrets:
          echo -n "${{ secrets.GPG_SIGNING_KEY }}" | base64 --decode | gpg --batch --import --passphrase-file passphrase.txt
          echo "-----------  gpg --edit-key ...  ---------------"
          # invoke 'gpg ... --edit-key ... trust':
          echo -e "5\ny\nquit" | gpg --batch --yes --pinentry-mode loopback --command-fd 0 --expert --edit-key 0436EE146A372544 trust
          echo "-----------  gpg --check-trustdb ...  ---------------"
          gpg --update-trustdb
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: "Display the current status of local GPG-storage:"
        run: |
          echo "- getting the list of available GPG-keys (in 'long'-format):"
          gpg --list-secret-keys --keyid-format=long
          echo "<details><summary><code>gpg --list-secret-keys --keyid-format=long</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          gpg --list-secret-keys --keyid-format=long >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          
          echo "- getting the list of available GPG-signatures (in '0xshort'-format):"
          gpg --list-signatures --keyid-format 0xshort
          echo "<details><summary><code>gpg --list-signatures --keyid-format 0xshort</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          gpg --list-signatures --keyid-format 0xshort >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY

      - name: "Signing the file 'pom.xml':"
        run: |
          echo "### Signing the file \'pom.xml\`" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          
          # invoke 'gpg ... --sign ...':
          .github/gpg/gpg-sign.sh pom.xml
          
          ls -laxo
          git status
          echo "------------ gpg --verify ... ---------------"
          gpg --verify pom.xml.asc
          echo "---------------------------------------------"
          
          echo "<details><summary><code>gpg --verify pom.xml.asc</code></summary>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          gpg --status-fd 1 --verify pom.xml.asc >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo -e "" >> $GITHUB_STEP_SUMMARY
